# .github/workflows/actiontest.yml

name: actiontest

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.5'

      - name: Build Go application
        run: go build -v ./...

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Tag, and Push to DockerHub
        env:
          NAME: minnnning
          REPO: actiontest
        run: |
          docker build -t $NAME/$REPO:latest .
          docker push $NAME/$REPO:latest
          
